# Digital Ocean App Platform Specification
# https://docs.digitalocean.com/products/app-platform/reference/app-spec/

name: clipdrop

services:
  - name: web
    dockerfile_path: Dockerfile
    github:
      # Update with your repository details
      repo: pedroanisio/clipdrop
      branch: main
      deploy_on_push: true

    # HTTP configuration
    http_port: 3000
    routes:
      - path: /

    # Instance configuration
    # Current slugs: apps-s-1vcpu-0.5gb ($5), apps-s-1vcpu-1gb ($12), apps-s-1vcpu-2gb ($25)
    # Dedicated: apps-d-1vcpu-0.5gb ($29), apps-d-1vcpu-1gb ($34), etc.
    # Legacy slugs (basic-xxs, basic-xs, etc.) only work for apps created before May 7, 2024
    instance_size_slug: apps-s-1vcpu-2gb
    instance_count: 1

    # Health check
    health_check:
      http_path: /login
      initial_delay_seconds: 10
      period_seconds: 30
      timeout_seconds: 5
      failure_threshold: 3

    # Environment variables
    envs:
      # Flask secret key (generate a new one for production)
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET

      # Encryption key for files at rest
      - key: ENCRYPTION_KEY
        scope: RUN_TIME
        type: SECRET

      # GitHub OAuth credentials
      - key: GITHUB_OAUTH_CLIENT_ID
        scope: RUN_TIME
        type: SECRET

      - key: GITHUB_OAUTH_CLIENT_SECRET
        scope: RUN_TIME
        type: SECRET

      # Database connection (set per app to isolate data)
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET

      # Storage configuration for Digital Ocean Spaces
      - key: STORAGE_TYPE
        scope: RUN_TIME
        value: s3

      - key: SPACES_BUCKET
        scope: RUN_TIME
        type: SECRET

      - key: SPACES_ENDPOINT
        scope: RUN_TIME
        value: https://nyc3.digitaloceanspaces.com

      - key: SPACES_REGION
        scope: RUN_TIME
        value: nyc3

      - key: SPACES_ACCESS_KEY
        scope: RUN_TIME
        type: SECRET

      - key: SPACES_SECRET_KEY
        scope: RUN_TIME
        type: SECRET

      - key: SPACES_PREFIX
        scope: RUN_TIME
        value: uploads

      # Flask environment
      - key: FLASK_ENV
        scope: RUN_TIME
        value: production

# Attach existing managed PostgreSQL database
# Set production: true and cluster_name to reference your existing managed database
# The cluster_name must match your existing DigitalOcean managed database cluster name
databases:
  - name: db
    engine: PG
    version: "16"
    production: true
    cluster_name: your-existing-cluster-name
